baseurl = "http://emmanuelthivierge.com"
title = "Emmanuel Thivierge personal site"
description = "Emmanuel Thivierge | Creative engineering; This site is the writings of my journey from a C++ 3D graphics programmer to a creative coder that use code to create interactive and immersive experiences and installations."

theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  title = "Emmanuel Thivierge | Creative engineering"
  description = '<!--[--> This site is the writings of my journey<!--]--><br />
                <!--[-->from a C++ 3D graphics programmer to a creative coder<!--]--><br />
                <!--[-->that use code to create interactive and immersive experiences and installations.<!--]-->'
  logo = "fa-home"
  copyright = "Emmanuel Thivierge"

[[params.social]]
  medium = "github"
  icon = "fa-github"
  link = "https://github.com/monamiman"

[[params.social]]
  medium = "linkedin"
  icon = "fa-linkedin"
  link = "https://www.linkedin.com/in/emmanuelthivierge/"